# Generated by Django 5.1.5 on 2025-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='cognak',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='vine',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='vodka',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='color',
            field=models.CharField(choices=[('light', 'Светлое'), ('semi-dark', 'Полутемное'), ('dark', 'Темное')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cognak',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Обьем'),
        ),
        migrations.AlterField(
            model_name='vine',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
