services:
  - type: web
    name: alcoland-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput &&
      echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'adminpass')" | python manage.py shell &&
      gunicorn alcoland.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alcoland.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        value: postgresql://alcoland_db_user:jW7Jz6atUSj2qJplS6c1Oxjx0uyFEgAa@dpg-d037i08dl3ps739jsi30-a.oregon-postgres.render.com/alcoland_db
    region: oregon
    rootDir: backend

