services:
  - type: web
    name: alcoland-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn alcoland.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alcoland.settings
      - key: PYTHON_VERSION
        value: 3.11
    region: oregon
    rootDir: backend
